
if game.PlaceId == 155615604 then
    local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
    local Windows = Library.CreateLib("Prison Life", "BloodTheme")
    -- MAIN
    local Main = Windows:NewTab("Main")
    local MainSection = Main:NewSection("Main")

    local WeaponSection = Main:NewSection("Weapon Section")
    -- Give Guns
    WeaponSection:NewDropdown("Choose a gun", "Gives LocalPlayer guns", {"M9", "Remington 870", "AK-47"}, function(v)
         local A_1 = game:GetService("Workspace")["Prison_ITEMS"].giver[v].ITEMPICKUP
         local Event = game:GetService("Workspace").Remote.ItemHandler
            Event:InvokeServer(A_1)
    end)

    -- Gun Mod
    WeaponSection:NewDropdown("Gun Mod", "Makes the gun op", {"M9","Remington 870", "AK-47"}, function(v)
        local module = nil
        if game:GetService("Players").LocalPlayer.Backpack:FindFirstChild(v) then
            module = require(game:GetService("Players").LocalPlayer.Backpack[v].GunStates)
        elseif game:GetService("Players").LocalPlayer.Character:FindFirstChild(v) then
            module = require(game:GetService("Players").LocalPlayer.Character[v].GunStates)
        end
        if module ~= nil then
            module["StoredAmmo"] = math.huge
            module["FireRate"] = 0.1
            module["Spread"] = 0
            module["Range"] = math.huge
            module["Bullets"] = 8
            module["ReloadTime"] = 0.000001
            module["AutoFire"] = true
            module["ReloadAnim"] = nil
        end
        

    end)

    -- PLAYER 
    local Player = Windows:NewTab("Player")
    local PlayerSection = Player:NewSection("Player")

    -- Walkspeeda
    PlayerSection:NewSlider("Walkspeed", "Changes the walkspeed of the player", 500, 16, function(s) -- 500 (MaxValue) | 0 (MinValue)
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
    end)
    -- JumpPower
    PlayerSection:NewSlider("JumpPower", "Changes the jump power of the player", 500, 50, function(s) -- 500 (MaxValue) | 0 (MinValue)
        game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
    end)
    -- InfiniJump
    PlayerSection:NewButton("Infinite Jump", "Makes the player able to jump infinitely", function()
        game:GetService("UserInputService").JumpRequest:connect(function()
            game:GetService("Players").LocalPlayer.Character:FindFirstChildOfClass("Humanoid"):ChangeState("Jumping")
    end)
    end)
    -- 
end
if game.PlaceId == 10675066724 then
    local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
    local Windows = Library.CreateLib("Slime Tower Tycoon", "BloodTheme")

    -- Autofarm tab
    local Autofarm = Windows:NewTab("Autofarm")
    
    
    -- AUTO FARM SECTION
    local AutofarmSection = Autofarm:NewSection("Autofarm")

    -- auto collect
    AutofarmSection:NewToggle("Auto Collect", "Automatically collects slime", function(state)
        getgenv().autocollect = state
        while wait() and getgenv().autocollect do
            for i,v in pairs(game:GetService("Workspace").Drops:GetChildren()) do
                if v.Name == "Dropper_Drop" then
                    v.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
                end
            end
        end
    end)
    -- auto sella
    AutofarmSection:NewToggle("Auto Sell", "Automatically sells slime", function(state)
        getgenv().autosell = state
        while wait() and getgenv().autosell do
            -- Script generated by R2Sv2
            -- R2Sv2 developed by Luckyxero
            
            local Event = game:GetService("ReplicatedStorage").GTycoonClient.Remotes.DepositDrops
            Event:FireServer()
            wait(3)

        end
    end)

    -- AUTOMATIC SECTION
    local AutomaticSection = Autofarm:NewSection("Income Purchase")

    -- auto buy speed
    AutomaticSection:NewToggle("Auto Buy Speed", "Automatically upgrades speed", function(state)
        getgenv().autobuy = state
        while wait() and getgenv().autobuy do
            -- Script generated by R2Sv2
            -- R2Sv2 developed by Luckyxero
             
            local Event = game:GetService("ReplicatedStorage").GTycoonClient.Remotes.BuySpeed
            Event:FireServer()
            wait()
            
        end
    end)

    -- auto buy slime
    --AutomaticSection:NewToggle("Auto Buy Slime", "Automatically upgrades slime", function(state)
    --    getgenv().autobuy = state
    --    while wait() and getgenv().autobuy do
    --        
   --         
   --     end
  --  end)
    -- auto merge slime
    AutomaticSection:NewToggle("Auto Merge Slime", "Automatically merges slime", function(state)
        getgenv().autobuy = state
        while wait() and getgenv().autobuy do
            -- Script generated by R2Sv2
            -- R2Sv2 developed by Luckyxero
            
            local Event = game:GetService("ReplicatedStorage").GTycoonClient.Remotes.MergeDroppers
            Event:FireServer()

            wait()

            
        end
    end)


end
